apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginapp
  labels:
    app: ginapp
spec:
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 64Mi