apiVersion: apps/v1
kind: Deployment
metadata:
  name: ginapp
spec:
  selector:
    matchLabels:
      app: ginapp
  template:
    metadata:
      labels:
        app: ginapp
    spec:
      containers:
      - name: myapp
        image: csighub.tencentyun.com/yuanhaojin/golang-web-app
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: csighub

